# Go Clean Architecture Application Configuration

# Server configuration
server:
  port: "8080"
  host: "localhost"
  read_timeout: "30s"
  write_timeout: "30s"
  idle_timeout: "120s"

# Database configuration
database:
  host: "postgres"
  port: 5432
  user: "postgres"
  password: "postgres"
  dbname: "go_clean_db"
  sslmode: "disable"
  max_open_conns: 25
  max_idle_conns: 5
  conn_max_lifetime: "5m"

# Redis configuration
redis:
  host: "redis"
  port: 6379
  password: ""
  db: 0
  pool_size: 10
  min_idle_conns: 5

# Logging configuration
logging:
  level: "info"
  format: "json"
  output: "stdout"

# Application configuration
app:
  name: "go-clean-api"
  version: "1.0.0"
  environment: "development"
  debug: true

# CORS configuration
cors:
  allowed_origins:
    - "http://localhost:3000"
    - "http://localhost:8080"
  allowed_methods:
    - "GET"
    - "POST"
    - "PUT"
    - "DELETE"
    - "OPTIONS"
  allowed_headers:
    - "Content-Type"
    - "Authorization"
    - "X-Requested-With"
  allow_credentials: true
  max_age: 86400

# Rate limiting configuration
rate_limit:
  enabled: true
  requests_per_minute: 100
  burst: 10

# Health check configuration
health:
  database_timeout: "5s"
  redis_timeout: "3s"

# Swagger/API Documentation configuration
swagger:
  enabled: true
  file_path: "./api/swagger.html"